import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Layout } from '@/components/Layout'
import { Children } from '@/types/global'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Next.js blog theme Avocado',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: Children) {
  return (
    <html lang="ko">
      <head>
        <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/xeicon@2.3.3/xeicon.min.css" />
      </head>

      <body className={inter.className}>
        <Layout.Container>
          <Layout.Header />
          
          {children}

          <Layout.Footer />
        </Layout.Container>
      </body>
    </html>
  )
}
